// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// LinkStorage is an autogenerated mock type for the LinkStorage type
type LinkStorage struct {
	mock.Mock
}

// GetFullURL provides a mock function with given fields: ctx, id
func (_m *LinkStorage) GetFullURL(ctx context.Context, id int64) (string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFullURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveFullURL provides a mock function with given fields: ctx, fullURL
func (_m *LinkStorage) SaveFullURL(ctx context.Context, fullURL string) (int64, error) {
	ret := _m.Called(ctx, fullURL)

	if len(ret) == 0 {
		panic("no return value specified for SaveFullURL")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, fullURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, fullURL)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, fullURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLinkStorage creates a new instance of LinkStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkStorage {
	mock := &LinkStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
