services:
  url-shortener:
    build: .
    image: url-shortener:latest
    container_name: url-shortener
    hostname: shortener
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000" # HTTP server
      - "8001:8001" # GRPC server
    depends_on:
      - postgres
    networks:
      - default

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    hostname: ${PG_HOST}
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DBNAME}
    # ports:
    # - "5432:5432"
    networks:
      - default

  # Миграции
  migrate:
    image: migrate/migrate:v4
    command: -path=/migrations -database "${PG_HOST}://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DBNAME}?sslmode=${DB_SSL_MODE}" up
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres
    networks:
      - default
